In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/clothes_market.csv')

In [ ]:
df.head()

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,discount,quantity,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason
0,ORD-33477,Huddie,Hoodie,Uniqlo,Brown,XS,Men,Silk,Summer,23.96,36%,18.0,276.02,13/06/2024,2024-06-21,Doha,Online,Cancelled,2.4,NaN
1,ORD-93931,Jacket Brown,Jacket,H&M,Brown,XXL,MEN,Nylon,Winter,166.89,32%,19.0,NaN,2023-09-14,18-09-2023,Amman,Debit Card,Delivered,2.9,Defective
2,ORD-28582,Hoodie Red,Hoodie,Forever21,Red,XS,Kids,Denim,Autumn,110.40 USD,13%,4.0,EGP 384.19,"December 30, 2024","January 01, 2025",Cairo,Credit Card,Pending,2.6,NaN
3,ORD-44084,Dress Blue,Dress,Adidas,Blue,M,Unisex,Linen,Summer,20.82,48%,12.0,-129.92,2024/07/02,"July 14, 2024",Dubai,Installment,Pending,4.8,Defective
4,ORD-76192,Blazer,Blazer,Levi's,Blue,s,women,Nylon,Spring,310.14,42%,15.0,2698.22,2023-08-10,NaN,Dubai,Debit Card,Processing,2.8,NaN

In [ ]:
df.head(20)

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,discount,quantity,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason
0,ORD-33477,Huddie,Hoodie,Uniqlo,Brown,XS,Men,Silk,Summer,23.96,36%,18.0,276.02,13/06/2024,2024-06-21,Doha,Online,Cancelled,2.4,NaN
1,ORD-93931,Jacket Brown,Jacket,H&M,Brown,XXL,MEN,Nylon,Winter,166.89,32%,19.0,NaN,2023-09-14,18-09-2023,Amman,Debit Card,Delivered,2.9,Defective
2,ORD-28582,Hoodie Red,Hoodie,Forever21,Red,XS,Kids,Denim,Autumn,110.40 USD,13%,4.0,EGP 384.19,"December 30, 2024","January 01, 2025",Cairo,Credit Card,Pending,2.6,NaN
3,ORD-44084,Dress Blue,Dress,Adidas,Blue,M,Unisex,Linen,Summer,20.82,48%,12.0,-129.92,2024/07/02,"July 14, 2024",Dubai,Installment,Pending,4.8,Defective
4,ORD-76192,Blazer,Blazer,Levi's,Blue,s,women,Nylon,Spring,310.14,42%,15.0,2698.22,2023-08-10,NaN,Dubai,Debit Card,Processing,2.8,NaN
5,ORD-99977,Blazer Black,Blazer,Gucci,Black,XL,Women,Nylon,NaN,337.42,0.06,6.0,1903.05 USD,2022-01-09,16-01-2022,Casablanca,Debit Card,Delivered,2.3,NaN
6,ORD-65884,Jeans Purple,JEANS,Zara,Purple,xs,Children,Wool,Spring,$113.48,49%,8.0,463.00 USD,07-21-2023,"July 25, 2023",riyadh,Credit Card,Pending,2.0,NaN
7,ORD-79008,Dress Yellow,Dress,H&M,Yellow,M,Men,Cotton,Spring,77.71,41%,NaN,641.88,NaN,"July 12, 2023",Beirut,Installment,Returned,2.7,NaN
8,ORD-31594,Coat Brown,Coat,Levi's,Brown,XX-L,Kids,Linen,Winter,190.10,33%,18.0,2292.61,NaN,2022/12/01,Dubay,Installment,Returned,3.7,NaN
9,ORD-95981,JEANS,Jeans,Uniqlo,White,M,Men,Nylon,Winter,209.19,13%,12.0,2183.94,2023-10-24,NaN,Dubay,Online,Delivered,2.3,NaN
10,ORD-67912,Sweater Pink,Sweater,Uniqlo,Pink,2XL,Men,Linen,Summer,464.10,17%,18.0,6933.65,"March 25, 2023",03-04-2023,Riyadh,Cash,Delivered,2.7,Changed mind
11,ORD-99276,Dress Green,Dresses,Puma,Green,2XL,Kids,Denim,Summer,421.63,28%,13.0,3891.64,04-07-2022,"April 20, 2022",Doha,Cash,Processing,6,Defective
12,ORD-85555,Hoodie,Hoodie,Gucci,Yellow,XS,Women,Linen,Winter,137.24 USD,9%,4.0,$499.55,"May 17, 2023",20-05-2023,Casablanca,Online,Pending,9,Late delivery
13,ORD-75507,Blazer Grey,blazer,Levi's,Grey,MEDIUM,Unisex,Nylon,Autumn,$453.61,0.25,10.0,3402.07,28-05-2023,2023/06/04,Tunis,Installment,Delivered,2.3,Changed mind
14,ORD-52759,Sweater,Sweater,Puma,Blue,S,Kids,Cotton,Summer,EGP 169.61,41%,7.0,700.49,09-29-2023,2023/10/10,عمان,Debit Card,Delivered,NaN,Wrong size
15,ORD-26128,Dress White,Dress,Nike,White,sm,Unisex,Wool,Autumn,31.02,34%,3.0,-61.42,NaN,2024-06-27,Doha,Installment,Processing,3.2,Late delivery
16,ORD-96308,T-Shirt,T-SHIRT,Zara,Brown,M,MALE,Wool,Spring,185.25,17%,20.0,$3075.15,15-08-2024,NaN,الدوحة,Credit Card,Processing,1.6,NaN
17,ORD-17011,Blazer,Blazer,Nike,Red,LARGE,Unisex,Linen,Spring,412.65,0.1,14.0,5199.39,10-21-2022,NaN,Doha,Debit Card,Processing,1.8,NaN
18,ORD-59175,T-Shirt Grey,T-Shirt,Gucci,Grey,XXL,child,Polyester,Autumn,478.53,26%,9.0,3187.01,2022/04/15,2022/04/22,Riyadh,Online,Processing,1.8,NaN
19,ORD-89895,Shorts,Short,mango,Green,XS,Women,NaN,Winter,114,20%,4.0,-365.92,2023-09-11,"September 19, 2023",riyadh,Cash,Processing,3.6,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         7120 non-null   object
 1   product_name     7120 non-null   object
 2   category         7120 non-null   object
 3   brand            7120 non-null   object
 4   color            6770 non-null   object
 5   size             7120 non-null   object
 6   gender           7120 non-null   object
 7   material         6740 non-null   object
 8   season           6774 non-null   object
 9   unit_price       6902 non-null   object
 10  discount         6767 non-null   object
 11  quantity         6564 non-null   float64
 12  total_sales      6338 non-null   object
 13  order_date       6395 non-null   object
 14  shipping_date    5935 non-null   object
 15  region           7120 non-null   object
 16  payment_method   7120 non-null   object
 17  order_status     7120 non-null   object
 18  customer_rating  6588 non-null   object
 19  return_reason    2889 non-null   object
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [ ]:
df.isna().sum()

order_id              0
product_name          0
category              0
brand                 0
color               350
size                  0
gender                0
material            380
season              346
unit_price          218
discount            353
quantity            556
total_sales         782
order_date          725
shipping_date      1185
region                0
payment_method        0
order_status          0
customer_rating     532
return_reason      4231
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(120)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['category'].unique()

array(['Hoodie', 'Jacket', 'Dress', 'Blazer', 'JEANS', 'Coat', 'Jeans',
       'Sweater', 'Dresses', 'blazer', 'T-SHIRT', 'T-Shirt', 'Short',
       'tshirt', 'Jeen', '  Skirt  ', 'Shorts', 'Shortz', 'BLAZER',
       'Jackt', 'Hoody', '  Sweater  ', 't_shirt', 'jackets',
       '  Shorts  ', '  Dress  ', 'Blaizer', 'shorts', 'COAT', 'sweater',
       'Skirt', 'Jeans ', 'Jaket', 'Coatt', '  T-Shirt  ', 'Kot', 'Blazr',
       'denim pants', 'dress', 'coat', 'Tshirts', 'Swater', 'skirts',
       'jeans', 'SWEATER', 'SKIRT', 'SHORTS', '  Jacket  ', 'sweters',
       'T shirt', 'Huddie', 'jacket', 'Sweter', 'JACKET', '  Hoodie  ',
       '  Coat  ', 'skirt', 'drss', 'DRESS', 'Skrt', 'hoodie', 'Jean',
       't-shirt', '  Blazer  ', 'hoodi', 'Dres', 'HOODIE', '  Jeans  '],
      dtype=object)

In [ ]:
df['category']=df['category'].str.strip()

In [ ]:
df['category']=df['category'].str.title()

In [ ]:
category_mapping = {

    # Hoodie
    'Hoody': 'Hoodie',
    'Huddie': 'Hoodie',
    'Hoodi': 'Hoodie',
    'Hoodi': 'Hoodie',
    'Hoodie': 'Hoodie',

    # Jacket
    'Jackt': 'Jacket',
    'Jaket': 'Jacket',
    'Jackets': 'Jacket',
    'Jacket': 'Jacket',

    # Dress
    'Dresses': 'Dress',
    'Dress': 'Dress',
    'Dres': 'Dress',
    'Drss': 'Dress',

    # Blazer
    'Blaizer': 'Blazer',
    'Blazr': 'Blazer',
    'Blazer': 'Blazer',

    # Jeans
    'Jeen': 'Jeans',
    'Jean': 'Jeans',
    'Jeans': 'Jeans',
    'Denim Pants': 'Jeans',

    # T-Shirt
    'Tshirt': 'T-Shirt',
    'T-Shirts': 'T-Shirt',
    'T Shirt': 'T-Shirt',
    'T_Shirt': 'T-Shirt',
    'T-Shirt': 'T-Shirt',

    # Shorts
    'Short': 'Shorts',
    'Shortz': 'Shorts',
    'Shorts': 'Shorts',

    # Sweater
    'Swater': 'Sweater',
    'Sweter': 'Sweater',
    'Sweters': 'Sweater',
    'Sweater': 'Sweater',

    # Coat
    'Coatt': 'Coat',
    'Kot': 'Coat',
    'Coat': 'Coat',

    # Skirt
    'Skrt': 'Skirt',
    'Skirts': 'Skirt',
    'Skirt': 'Skirt'
}

In [ ]:
df['category']=df['category'].replace(category_mapping)

In [ ]:
df['category'].unique()

array(['Hoodie', 'Jacket', 'Dress', 'Blazer', 'Jeans', 'Coat', 'Sweater',
       'T-Shirt', 'Shorts', 'Skirt', 'Tshirts'], dtype=object)

In [ ]:
df['category'].value_counts()

category
Dress      719
Sweater    718
Jacket     716
Jeans      716
Coat       714
Skirt      702
Hoodie     693
Blazer     682
T-Shirt    672
Shorts     623
Tshirts     45
Name: count, dtype: int64

In [ ]:
df['product_name'].unique()

array(['Huddie', 'Jacket Brown', 'Hoodie Red', 'Dress Blue', 'Blazer',
       'Blazer Black', 'Jeans Purple', 'Dress Yellow', 'Coat Brown',
       'JEANS', 'Sweater Pink', 'Dress Green', 'Hoodie', 'Blazer Grey',
       'Sweater', 'Dress White', 'T-Shirt', 'T-Shirt Grey', 'Shorts',
       'T-Shirt White', 'Coat', 'Jeans ', 'Skirt Red', 'Jeans Blue',
       'Shorts Brown', 'Jeans', 'Blazer Purple', 'T-Shirt Yellow',
       'Blazer Brown', 'Jacket Black', 'Dress Grey', 'Hoodie Pink',
       'sweters', 'Jacket White', 'T-Shirt Red', 'Shorts Pink', 'Jaket',
       'Sweater White', 'Hoodie Blue', 'Shorts Blue', 'Hoodie Brown',
       'Dress', 'tshirt', 'BLAZER', 'Shorts Green', 'coat', 'Sweater Red',
       'Hoodie Grey', 'Blazer White', 'SHORTS', 'Skrt', 'Jacket Red',
       'Jeans Green', 'T-Shirt Purple', 'Sweter', 'Jacket Blue',
       'Skirt Green', 'Jeen', 'Skirt', 'Shorts White', 'Blazer Red',
       'Coat Pink', 'Jeans Red', 'T shirt', 'Coat White', 'Jeans Black',
       'Hoodie Yellow', 'Blazer Pink', 'Blazer Yellow', 'sweater',
       'Blazer Blue', 'Jacket Purple', 'Skirt Yellow', 'Dress Black',
       'Coatt', 'Coat Blue', 'Hoodie Purple', 'T-Shirt Pink', 'jacket',
       'Jacket', 'Coat Grey', 'T-Shirt Brown', 'Skirt Grey', 'Skirt Pink',
       'Shorts Yellow', 'Jacket Pink', 'Sweater Blue', 'Jeans Grey',
       'Jeans Pink', 'Skirt Blue', 'Coat Red', 'Shorts Purple', 'Blazr',
       'Sweater Black', 'hoodi', 'Jacket Yellow', 'Sweater Brown',
       '  Jacket  ', 'Short', 'Tshirts', '  T-Shirt  ', 'T-Shirt Blue',
       'SKIRT', 'shorts', 'COAT', 'Shortz', 'Coat Green', 'Coat Yellow',
       'Dress Pink', 'Hoodie White', 'blazer', 'Hoodie Green',
       'Coat Black', 'Hoodie Black', 't-shirt', 'Sweater Purple',
       'JACKET', 'Skirt Brown', 'Dress Purple', 'skirt', 'denim pants',
       'SWEATER', 'Dress Brown', 'Skirt White', 'Sweater Grey',
       'Blazer Green', 'Hoody', 'Shorts Black', 'Jean', 'DRESS',
       'Jacket Green', '  Dress  ', 'dress', 'drss', 'Jackt', 'jeans',
       'Swater', '  Blazer  ', 'Sweater Green', 't_shirt', 'Jacket Grey',
       'Dress Red', 'Sweater Yellow', 'Blaizer', 'T-Shirt Green',
       'Shorts Grey', 'Skirt Black', 'Jeans Brown', 'Jeans White',
       'Jeans Yellow', 'Skirt Purple', 'Kot', '  Shorts  ', '  Hoodie  ',
       'Coat Purple', '  Jeans  ', 'Dresses', '  Sweater  ', 'hoodie',
       'HOODIE', 'T-SHIRT', '  Skirt  ', 'T-Shirt Black', 'skirts',
       'Dres', '  Coat  ', 'jackets', 'Shorts Red'], dtype=object)

In [ ]:
df['product_name'] = df['product_name'].str.strip().str.title()

In [ ]:
colors=['Brown','Red','White','Purple','Yellow','Grey','Black','Green','Pink','Blue']

In [ ]:
pattern='|'.join(colors)

In [ ]:
df['product_name']=df['product_name'].str.replace(f'\\b({pattern})\\b','',regex=True).str.strip()

In [ ]:
df['product_name'].unique()

array(['Huddie', 'Jacket', 'Hoodie', 'Dress', 'Blazer', 'Jeans', 'Coat',
       'Sweater', 'T-Shirt', 'Shorts', 'Skirt', 'Sweters', 'Jaket',
       'Tshirt', 'Skrt', 'Sweter', 'Jeen', 'T Shirt', 'Coatt', 'Blazr',
       'Hoodi', 'Short', 'Tshirts', 'Shortz', 'Denim Pants', 'Hoody',
       'Jean', 'Drss', 'Jackt', 'Swater', 'T_Shirt', 'Blaizer', 'Kot',
       'Dresses', 'Skirts', 'Dres', 'Jackets'], dtype=object)

In [ ]:
product_name_mapping = {
    'Huddie': 'Hoodie',
    'Hoody': 'Hoodie',
    'Hoodi': 'Hoodie',

    'Jackt': 'Jacket',
    'Jaket': 'Jacket',
    'Jackets': 'Jacket',

    'Drss': 'Dress',
    'Dres': 'Dress',
    'Dresses': 'Dress',

    'Blaizer': 'Blazer',
    'Blazr': 'Blazer',

    'Jeen': 'Jeans',
    'Jean': 'Jeans',
    'Denim Pants': 'Jeans',

    'Swater': 'Sweater',
    'Sweter': 'Sweater',
    'Sweters': 'Sweater',

    'Coatt': 'Coat',
    'Kot': 'Coat',

    'Skrt': 'Skirt',
    'Skirts': 'Skirt',

    'Short': 'Shorts',
    'Shortz': 'Shorts',

    'Tshirt': 'T-Shirt',
    'Tshirts': 'T-Shirt',
    'T Shirt': 'T-Shirt',
    'T_Shirt': 'T-Shirt'
}

In [ ]:
df['product_name']=df['product_name'].replace(product_name_mapping)

In [ ]:
df['product_name'].unique()

array(['Hoodie', 'Jacket', 'Dress', 'Blazer', 'Jeans', 'Coat', 'Sweater',
       'T-Shirt', 'Shorts', 'Skirt'], dtype=object)

In [ ]:
df['brand'].unique()

array(['Uniqlo', 'H&M', 'Forever21', 'Adidas', "Levi's", 'Gucci', 'Zara',
       'Puma', 'Nike', 'mango', 'Mango', 'forever21', 'puma', 'FOREVER21',
       'nike', 'UNIQLO', 'zara', 'PUMA', "LEVI'S", 'ADIDAS', 'ZARA',
       'uniqlo', 'h&m', 'GUCCI', 'gucci', 'NIKE', "levi's", 'MANGO',
       'adidas'], dtype=object)

In [ ]:
df['brand']=df['brand'].str.strip().str.title()

In [ ]:
df['brand'].unique()

array(['Uniqlo', 'H&M', 'Forever21', 'Adidas', "Levi'S", 'Gucci', 'Zara',
       'Puma', 'Nike', 'Mango'], dtype=object)

In [ ]:
df['color'].unique()

array(['Brown', 'Red', 'Blue', 'Black', 'Purple', 'Yellow', 'White',
       'Pink', 'Green', 'Grey', nan], dtype=object)

In [ ]:
df['color']=df['color'].fillna('UnKnown')

In [ ]:
df['color'].unique()

array(['Brown', 'Red', 'Blue', 'Black', 'Purple', 'Yellow', 'White',
       'Pink', 'Green', 'Grey', 'UnKnown'], dtype=object)

In [ ]:
df.isna().sum()

order_id              0
product_name          0
category              0
brand                 0
color                 0
size                  0
gender                0
material            375
season              339
unit_price          213
discount            348
quantity            547
total_sales         772
order_date          708
shipping_date      1167
region                0
payment_method        0
order_status          0
customer_rating     525
return_reason      4161
dtype: int64

In [ ]:
df['size'].unique()

array(['XS', 'XXL', 'M', 's', 'XL', 'xs', 'XX-L', '2XL', 'MEDIUM', 'S',
       'sm', 'LARGE', '  XS  ', 'L', 'extra large', 'xxl', 'Lg', 'm',
       'xl', 'large', 'Sm', 'SMALL', 'l', 'medium', 'X-S', 'xlarge', 'lg',
       'double xl', 'X-L', 'small', '  M  ', 'xsmall', 'extra small',
       '2xl', '  L  ', '  XXL  ', 'XLARGE', '  XL  ', 'med', 'Med',
       '  S  '], dtype=object)

In [ ]:
df['size']=df['size'].str.strip().str.title()

In [ ]:
df['size'].unique()

array(['Xs', 'Xxl', 'M', 'S', 'Xl', 'Xx-L', '2Xl', 'Medium', 'Sm',
       'Large', 'L', 'Extra Large', 'Lg', 'Small', 'X-S', 'Xlarge',
       'Double Xl', 'X-L', 'Xsmall', 'Extra Small', 'Med'], dtype=object)

In [ ]:
size_mapping={
    'S':'Small',
    'Sm':'Small',
    'XS':'Extra Small',
    'Xs':'Extra Small',
    'X-S':'Extra Small',
    'Xsmall':'Extra Small',
    'M':'Medium',
    'Med':'Medium',
    'Md':'Medium',
    'L':'Large',
    'Lg':'Large',
    'XL':'Extra Large',
    'Xlarge':'Extra Large',
    'X-L':'Extra Large',
    'Xl':'Extra Large',
    'XXL:':'Extra Extra Large',
    'Xxl':'Extra Extra Large',
    'Xx-L':'Extra Extra Large',
    'Double Xl':'Extra Extra Large',
    '2Xl':'Extra Extra Large'

}

In [ ]:
df['size']=df['size'].replace(size_mapping)

In [ ]:
df['size'].unique()

array(['Extra Small', 'Extra Extra Large', 'Medium', 'Small',
       'Extra Large', 'Large'], dtype=object)

In [ ]:
df['size'].value_counts()

size
Large                1206
Extra Extra Large    1171
Small                1169
Medium               1166
Extra Small          1147
Extra Large          1141
Name: count, dtype: int64

In [ ]:
df['size'].isna().sum()

np.int64(0)

In [ ]:
df['gender'].unique()

array(['Men', 'MEN', 'Kids', 'Unisex', 'women', 'Women', 'Children',
       '  Women  ', 'MALE', 'child', 'unisex', 'WOMEN', 'men', 'Child',
       'male', '  Men  ', 'Male', '  Unisex  ', 'both', 'uni', 'UNISEX',
       'childrens', 'KIDS', 'female', '  Kids  ', 'FEMALE', 'Female',
       'Woman', 'F', 'kids', 'M'], dtype=object)

In [ ]:
df['gender'] = df['gender'].str.strip().str.lower()

In [ ]:
df['gender'].unique()

array(['men', 'kids', 'unisex', 'women', 'children', 'male', 'child',
       'both', 'uni', 'childrens', 'female', 'woman', 'f', 'm'],
      dtype=object)

In [ ]:
sex_mapping = {

    # Male
    'men': 'Male',
    'male': 'Male',
    'm': 'Male',

    # Female
    'women': 'Female',
    'woman': 'Female',
    'female': 'Female',
    'f': 'Female',

    # Kids
    'kids': 'Kids',
    'kid': 'Kids',
    'child': 'Kids',
    'children': 'Kids',
    'childrens': 'Kids',

    # Unisex
    'unisex': 'Unisex',
    'uni': 'Unisex',
    'both': 'Unisex',

}

In [ ]:
df['gender']=df['gender'].replace(sex_mapping)

In [ ]:
df['gender'].unique()

array(['Male', 'Kids', 'Unisex', 'Female'], dtype=object)

In [ ]:
df['gender'].value_counts()

gender
Unisex    1847
Male      1747
Kids      1718
Female    1688
Name: count, dtype: int64

In [ ]:
df['material'].unique()

array(['Silk', 'Nylon', 'Denim', 'Linen', 'Wool', 'Cotton', 'Polyester',
       nan, 'Leather'], dtype=object)

In [ ]:
df['material']=df['material'].str.strip()

In [ ]:
df['material'].isna().sum()

np.int64(375)

In [ ]:
df['material']=df['material'].fillna(df['material'].mode()[0])

In [ ]:
df['material'].isna().sum()

np.int64(0)

In [ ]:
df['season'].unique()

array(['Summer', 'Winter', 'Autumn', 'Spring', nan], dtype=object)

In [ ]:
df[df['season'].isna()]

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,discount,quantity,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason
5,ORD-99977,Blazer,Blazer,Gucci,Black,Extra Large,Female,Nylon,NaN,337.42,0.06,6.0,1903.05 USD,2022-01-09,16-01-2022,Casablanca,Debit Card,Delivered,2.3,NaN
34,ORD-81921,Sweater,Sweater,Uniqlo,UnKnown,Medium,Male,Wool,NaN,67.62,10%,13.0,NaN,05-16-2024,"May 21, 2024",tunis,Installment,Cancelled,3.6,NaN
38,ORD-24479,Shorts,Shorts,Levi'S,Pink,Large,Kids,Denim,NaN,$17.21,NaN,6.0,$68.15,NaN,13/02/2022,Doha,Credit Card,Processing,2.7,NaN
55,ORD-74711,Blazer,Blazer,Puma,White,Small,Male,Linen,NaN,255.19,26%,8.0,EGP 1510.72,2022/04/06,NaN,Alexandria,Credit Card,Pending,2.1,Changed mind
91,ORD-69522,Blazer,Blazer,Mango,Yellow,Large,Male,Silk,NaN,336.87,19%,2.0,545.73,27/02/2022,03-09-2022,Amman,Cash,Returned,4.5/5,Defective
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6926,ORD-93579,Blazer,Blazer,Adidas,Pink,Extra Small,Male,Silk,NaN,96.67,7%,20.0,NaN,14/08/2023,17/08/2023,Tunis,Credit Card,Returned,1.4,Wrong size
6963,ORD-84338,Shorts,Shorts,Gucci,Black,Large,Kids,Nylon,NaN,313.21 USD,NaN,14.0,3201.01,2023-04-21,2023-05-05,كازابلانكا,Installment,Processing,2.3,Changed mind
7026,ORD-62444,Blazer,Blazer,Puma,White,Extra Extra Large,Kids,Silk,NaN,403.10,0.17,9.0,$3011.16,12/02/2023,02-20-2023,Beirut,Online,Returned,3.8,NaN
7034,ORD-49860,Sweater,Sweater,Forever21,Green,Extra Large,Unisex,Denim,NaN,249.72,16%,8.0,1678.12,22-06-2023,"June 29, 2023",Cairo,Credit Card,Processing,3.3,NaN
7070,ORD-81683,Sweater,Sweater,Zara,Pink,Large,Kids,Linen,NaN,59.94,20%,8.0,-383.62,2022-06-09,"June 10, 2022",Alex,Cash,Delivered,1.5,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7000 entries, 0 to 7119
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         7000 non-null   object
 1   product_name     7000 non-null   object
 2   category         7000 non-null   object
 3   brand            7000 non-null   object
 4   color            7000 non-null   object
 5   size             7000 non-null   object
 6   gender           7000 non-null   object
 7   material         7000 non-null   object
 8   season           6661 non-null   object
 9   unit_price       6787 non-null   object
 10  discount         6652 non-null   object
 11  quantity         6453 non-null   float64
 12  total_sales      6228 non-null   object
 13  order_date       6292 non-null   object
 14  shipping_date    5833 non-null   object
 15  region           7000 non-null   object
 16  payment_method   7000 non-null   object
 17  order_status     7000 non-null   object
 18  customer_rating  6475 non-null   object
 19  return_reason    2839 non-null   object
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [ ]:
df['unit_price']=df['unit_price'].str.extract(r'(\-?\d+\.?\d*)')

In [ ]:
df.head(20)

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,discount,quantity,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason
0,ORD-33477,Hoodie,Hoodie,Uniqlo,Brown,Extra Small,Male,Silk,Summer,23.96,36%,18.0,276.02,13/06/2024,2024-06-21,Doha,Online,Cancelled,2.4,NaN
1,ORD-93931,Jacket,Jacket,H&M,Brown,Extra Extra Large,Male,Nylon,Winter,166.89,32%,19.0,NaN,2023-09-14,18-09-2023,Amman,Debit Card,Delivered,2.9,Defective
2,ORD-28582,Hoodie,Hoodie,Forever21,Red,Extra Small,Kids,Denim,Autumn,110.40,13%,4.0,EGP 384.19,"December 30, 2024","January 01, 2025",Cairo,Credit Card,Pending,2.6,NaN
3,ORD-44084,Dress,Dress,Adidas,Blue,Medium,Unisex,Linen,Summer,20.82,48%,12.0,-129.92,2024/07/02,"July 14, 2024",Dubai,Installment,Pending,4.8,Defective
4,ORD-76192,Blazer,Blazer,Levi'S,Blue,Small,Female,Nylon,Spring,310.14,42%,15.0,2698.22,2023-08-10,NaN,Dubai,Debit Card,Processing,2.8,NaN
5,ORD-99977,Blazer,Blazer,Gucci,Black,Extra Large,Female,Nylon,NaN,337.42,0.06,6.0,1903.05 USD,2022-01-09,16-01-2022,Casablanca,Debit Card,Delivered,2.3,NaN
6,ORD-65884,Jeans,Jeans,Zara,Purple,Extra Small,Kids,Wool,Spring,113.48,49%,8.0,463.00 USD,07-21-2023,"July 25, 2023",riyadh,Credit Card,Pending,2.0,NaN
7,ORD-79008,Dress,Dress,H&M,Yellow,Medium,Male,Cotton,Spring,77.71,41%,NaN,641.88,NaN,"July 12, 2023",Beirut,Installment,Returned,2.7,NaN
8,ORD-31594,Coat,Coat,Levi'S,Brown,Extra Extra Large,Kids,Linen,Winter,190.10,33%,18.0,2292.61,NaN,2022/12/01,Dubay,Installment,Returned,3.7,NaN
9,ORD-95981,Jeans,Jeans,Uniqlo,White,Medium,Male,Nylon,Winter,209.19,13%,12.0,2183.94,2023-10-24,NaN,Dubay,Online,Delivered,2.3,NaN
10,ORD-67912,Sweater,Sweater,Uniqlo,Pink,Extra Extra Large,Male,Linen,Summer,464.10,17%,18.0,6933.65,"March 25, 2023",03-04-2023,Riyadh,Cash,Delivered,2.7,Changed mind
11,ORD-99276,Dress,Dress,Puma,Green,Extra Extra Large,Kids,Denim,Summer,421.63,28%,13.0,3891.64,04-07-2022,"April 20, 2022",Doha,Cash,Processing,6,Defective
12,ORD-85555,Hoodie,Hoodie,Gucci,Yellow,Extra Small,Female,Linen,Winter,137.24,9%,4.0,$499.55,"May 17, 2023",20-05-2023,Casablanca,Online,Pending,9,Late delivery
13,ORD-75507,Blazer,Blazer,Levi'S,Grey,Medium,Unisex,Nylon,Autumn,453.61,0.25,10.0,3402.07,28-05-2023,2023/06/04,Tunis,Installment,Delivered,2.3,Changed mind
14,ORD-52759,Sweater,Sweater,Puma,Blue,Small,Kids,Cotton,Summer,169.61,41%,7.0,700.49,09-29-2023,2023/10/10,عمان,Debit Card,Delivered,NaN,Wrong size
15,ORD-26128,Dress,Dress,Nike,White,Small,Unisex,Wool,Autumn,31.02,34%,3.0,-61.42,NaN,2024-06-27,Doha,Installment,Processing,3.2,Late delivery
16,ORD-96308,T-Shirt,T-Shirt,Zara,Brown,Medium,Male,Wool,Spring,185.25,17%,20.0,$3075.15,15-08-2024,NaN,الدوحة,Credit Card,Processing,1.6,NaN
17,ORD-17011,Blazer,Blazer,Nike,Red,Large,Unisex,Linen,Spring,412.65,0.1,14.0,5199.39,10-21-2022,NaN,Doha,Debit Card,Processing,1.8,NaN
18,ORD-59175,T-Shirt,T-Shirt,Gucci,Grey,Extra Extra Large,Kids,Polyester,Autumn,478.53,26%,9.0,3187.01,2022/04/15,2022/04/22,Riyadh,Online,Processing,1.8,NaN
19,ORD-89895,Shorts,Shorts,Mango,Green,Extra Small,Female,Silk,Winter,114,20%,4.0,-365.92,2023-09-11,"September 19, 2023",riyadh,Cash,Processing,3.6,NaN

In [ ]:
df['unit_price']=pd.to_numeric(df['unit_price'],errors='coerce')

In [ ]:
df['unit_price'].describe()

count    6787.000000
mean      243.035621
std       159.793417
min      -496.060000
25%       121.145000
50%       249.570000
75%       373.645000
max       499.910000
Name: unit_price, dtype: float64

In [ ]:
df['unit_price'].isna().sum()

np.int64(213)

In [ ]:
df['unit_price']=df['unit_price'].fillna(df['unit_price'].mean())

In [ ]:
df['unit_price'].isna().sum()

np.int64(0)

In [ ]:
df['discount'].unique()

array(['36%', '32%', '13%', '48%', '42%', '0.06', '49%', '41%', '33%',
       '17%', '28%', '9%', '0.25', '34%', '0.1', '26%', '20%', '0.46',
       nan, '11%', '0.14', '16%', '0.36', '10%', '38%', '40%', '0.02',
       '0%', '7%', '43%', '14%', '23%', '4%', '15%', '25%', '0.44', '18%',
       '39%', '44%', '2%', '6%', '22%', '46%', '35%', '21%', '0.09',
       '19%', '1%', '50%', '31%', '3%', '12%', '47%', '27%', '37%',
       '0.43', '8%', '45%', '30%', '24%', '0.0', '5%', '0.21', '0.27',
       '0.19', '0.17', '0.49', '0.34', '0.07', '0.03', '0.5', '0.23',
       '0.47', '0.13', '0.41', '0.32', '0.48', '0.38', '0.12', '0.39',
       '0.45', '0.22', '0.26', '0.05', '0.04', '0.42', '0.33', '0.31',
       '0.2', '0.15', '0.37', '0.35', '0.29', '0.16', '0.18', '0.28',
       '0.11', '0.01', '0.4', '0.3', '0.08', '0.24'], dtype=object)

In [ ]:
def convert_discount(value):
    if pd.isna(value):
        return 0
    value=str(value).strip()
    if '%' in value:
        return float(value.replace('%', '')) / 100
    return float(value)

In [ ]:
df['discount']=df['discount'].apply(convert_discount)

In [ ]:
df['discount'].unique()

array([0.36, 0.32, 0.13, 0.48, 0.42, 0.06, 0.49, 0.41, 0.33, 0.17, 0.28,
       0.09, 0.25, 0.34, 0.1 , 0.26, 0.2 , 0.46, 0.  , 0.11, 0.14, 0.16,
       0.38, 0.4 , 0.02, 0.07, 0.43, 0.23, 0.04, 0.15, 0.44, 0.18, 0.39,
       0.22, 0.35, 0.21, 0.19, 0.01, 0.5 , 0.31, 0.03, 0.12, 0.47, 0.27,
       0.37, 0.08, 0.45, 0.3 , 0.24, 0.05, 0.29])

In [ ]:
df['discount'].isna().sum()

np.int64(0)

In [ ]:
df[df['unit_price'] < 0]

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,discount,quantity,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason
113,ORD-87116,Jacket,Jacket,Levi'S,Blue,Extra Small,Female,Leather,Autumn,-337.39,0.40,NaN,2631.64,NaN,03/08/2023,Alexandria,Cash,Processing,2.1,NaN
156,ORD-67172,Hoodie,Hoodie,H&M,Red,Extra Small,Male,Wool,Spring,-239.03,0.35,3.0,$466.11,2024/08/30,09-09-2024,Alexandria,Online,Cancelled,5.0,Changed mind
165,ORD-61441,Blazer,Blazer,Gucci,UnKnown,Extra Extra Large,Unisex,Wool,Autumn,-125.67,0.00,18.0,2262.06,2024/06/28,2024/06/30,Riyadh,Online,Cancelled,1.6,Wrong size
201,ORD-70169,Sweater,Sweater,Mango,Brown,Extra Small,Male,Silk,Summer,-26.19,0.03,10.0,$254.04,02-04-2022,15-04-2022,Doha,Debit Card,Delivered,1.7,NaN
269,ORD-40135,Jeans,Jeans,H&M,UnKnown,Medium,Unisex,Nylon,Autumn,-148.95,0.44,1.0,83.41,"February 20, 2023",03-01-2023,Cairo,Cash,Cancelled,3.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6882,ORD-67126,Blazer,Blazer,Puma,Blue,Small,Kids,Leather,Spring,-307.37,0.04,-9.0,2655.68,"March 31, 2023",NaN,Doha,Installment,Cancelled,4.9/5,NaN
6981,ORD-95338,Skirt,Skirt,Zara,Yellow,Extra Large,Male,Silk,Summer,-128.02,0.49,9.0,587.61,05-26-2022,"June 09, 2022",beirut,Debit Card,Delivered,NaN,Changed mind
6990,ORD-72012,T-Shirt,T-Shirt,Nike,Black,Large,Female,Silk,Spring,-166.23,0.00,18.0,-2992.14,27-12-2024,NaN,Kuwait,debit card,Delivered,4.8,Changed mind
7061,ORD-97867,Coat,Coat,Puma,Yellow,Extra Extra Large,Male,Leather,Summer,-345.49,0.42,5.0,1001.92,"January 06, 2024","January 14, 2024",Riyadh,Credit Card,Pending,3.4,Wrong size
7088,ORD-17706,Jacket,Jacket,Levi'S,Purple,Extra Small,Male,Wool,Summer,-14.39,0.28,9.0,93.25,04-09-2024,23-04-2024,Beirut,Debit Card,Returned,3.3,NaN

In [ ]:
df['invalid_price_flag'] = df['unit_price'] < 0

In [ ]:
df['invalid_quantity_flag'] = df['quantity'] <= 0

In [ ]:
df['invalid_price_flag'].mean() * 100

np.float64(2.314285714285714)

In [ ]:
clean_df = df[
    (df['unit_price'] >= 0) &
    (df['quantity'] > 0)
].copy()

In [ ]:
clean_df.shape

(6008, 22)

In [ ]:
clean_df.head()

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,...,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason,invalid_price_flag,invalid_quantity_flag
0,ORD-33477,Hoodie,Hoodie,Uniqlo,Brown,Extra Small,Male,Silk,Summer,23.96,...,276.02,13/06/2024,2024-06-21,Doha,Online,Cancelled,2.4,NaN,False,False
1,ORD-93931,Jacket,Jacket,H&M,Brown,Extra Extra Large,Male,Nylon,Winter,166.89,...,NaN,2023-09-14,18-09-2023,Amman,Debit Card,Delivered,2.9,Defective,False,False
2,ORD-28582,Hoodie,Hoodie,Forever21,Red,Extra Small,Kids,Denim,Autumn,110.40,...,EGP 384.19,"December 30, 2024","January 01, 2025",Cairo,Credit Card,Pending,2.6,NaN,False,False
3,ORD-44084,Dress,Dress,Adidas,Blue,Medium,Unisex,Linen,Summer,20.82,...,-129.92,2024/07/02,"July 14, 2024",Dubai,Installment,Pending,4.8,Defective,False,False
4,ORD-76192,Blazer,Blazer,Levi'S,Blue,Small,Female,Nylon,Spring,310.14,...,2698.22,2023-08-10,NaN,Dubai,Debit Card,Processing,2.8,NaN,False,False

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6008 entries, 0 to 7119
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               6008 non-null   object
 1   product_name           6008 non-null   object
 2   category               6008 non-null   object
 3   brand                  6008 non-null   object
 4   color                  6008 non-null   object
 5   size                   6008 non-null   object
 6   gender                 6008 non-null   object
 7   material               6008 non-null   object
 8   season                 5717 non-null   object
 9   unit_price             6008 non-null   float64
 10  discount               6008 non-null   float64
 11  quantity               6008 non-null   float64
 12  total_sales            5344 non-null   object
 13  order_date             5397 non-null   object
 14  shipping_date          4999 non-null   object
 15  region                 6008 non-null   object
 16  payment_method         6008 non-null   object
 17  order_status           6008 non-null   object
 18  customer_rating        5547 non-null   object
 19  return_reason          2433 non-null   object
 20  invalid_price_flag     6008 non-null   bool
 21  invalid_quantity_flag  6008 non-null   bool
dtypes: bool(2), float64(3), object(17)
memory usage: 997.4+ KB

In [ ]:
clean_df['total_sales']=clean_df['total_sales'].str.extract(r'(\-?\d+\.?\d*)')

In [ ]:
clean_df['total_sales']=pd.to_numeric(clean_df['total_sales'],errors='coerce')

In [ ]:
clean_df['total_sales'].describe()

count    5344.000000
mean     1916.031097
std      1839.045929
min     -7358.320000
25%       547.845000
50%      1450.655000
75%      2916.167500
max      9059.910000
Name: total_sales, dtype: float64

In [ ]:
negative_sales = clean_df[clean_df['total_sales'] < 0]

In [ ]:
negative_sales['order_status'].value_counts()

order_status
Processing    25
Returned      21
Cancelled     19
Pending       18
Delivered     18
processing     1
returned       1
pending        1
delivered      1
cancelled      1
Name: count, dtype: int64

In [ ]:
clean_df

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,...,total_sales,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason,invalid_price_flag,invalid_quantity_flag
0,ORD-33477,Hoodie,Hoodie,Uniqlo,Brown,Extra Small,Male,Silk,Summer,23.96,...,276.02,13/06/2024,2024-06-21,Doha,Online,Cancelled,2.4,NaN,False,False
1,ORD-93931,Jacket,Jacket,H&M,Brown,Extra Extra Large,Male,Nylon,Winter,166.89,...,NaN,2023-09-14,18-09-2023,Amman,Debit Card,Delivered,2.9,Defective,False,False
2,ORD-28582,Hoodie,Hoodie,Forever21,Red,Extra Small,Kids,Denim,Autumn,110.40,...,384.19,"December 30, 2024","January 01, 2025",Cairo,Credit Card,Pending,2.6,NaN,False,False
3,ORD-44084,Dress,Dress,Adidas,Blue,Medium,Unisex,Linen,Summer,20.82,...,-129.92,2024/07/02,"July 14, 2024",Dubai,Installment,Pending,4.8,Defective,False,False
4,ORD-76192,Blazer,Blazer,Levi'S,Blue,Small,Female,Nylon,Spring,310.14,...,2698.22,2023-08-10,NaN,Dubai,Debit Card,Processing,2.8,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,ORD-84524,T-Shirt,Tshirts,Forever21,Green,Medium,Male,Nylon,Winter,443.27,...,2938.88,2024/08/26,29-08-2024,Casablanca,Debit Card,Pending,NaN,NaN,False,False
7114,ORD-58627,Jeans,Jeans,H&M,Yellow,Extra Small,Female,Linen,Autumn,364.27,...,1049.10,2022/01/02,2022-01-03,Amman,Installment,Cancelled,1.3,NaN,False,False
7116,ORD-88951,Dress,Dress,H&M,Green,Extra Extra Large,Male,Leather,Summer,373.65,...,3885.96,01/05/2024,02/05/2024,Riyadh,Debit Card,Delivered,2.9,Wrong size,False,False
7117,ORD-24646,Coat,Coat,Zara,Brown,Medium,Kids,Polyester,Winter,395.10,...,4812.32,02-11-2024,22/02/2024,Dubai,Credit Card,Processing,1.4,Late delivery,False,False
7119,ORD-65256,Coat,Coat,Nike,Blue,Extra Extra Large,Unisex,Denim,Winter,247.43,...,1425.20,2022-10-26,2022/11/03,DUBAI,installment,Pending,3.6,NaN,False,False

In [ ]:
clean_df['calculated_Revenue'] = (clean_df['unit_price'] * clean_df['quantity'])-(1-clean_df['discount'])

In [ ]:
clean_df

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,...,order_date,shipping_date,region,payment_method,order_status,customer_rating,return_reason,invalid_price_flag,invalid_quantity_flag,calculated_Revenue
0,ORD-33477,Hoodie,Hoodie,Uniqlo,Brown,Extra Small,Male,Silk,Summer,23.96,...,13/06/2024,2024-06-21,Doha,Online,Cancelled,2.4,NaN,False,False,430.64
1,ORD-93931,Jacket,Jacket,H&M,Brown,Extra Extra Large,Male,Nylon,Winter,166.89,...,2023-09-14,18-09-2023,Amman,Debit Card,Delivered,2.9,Defective,False,False,3170.23
2,ORD-28582,Hoodie,Hoodie,Forever21,Red,Extra Small,Kids,Denim,Autumn,110.40,...,"December 30, 2024","January 01, 2025",Cairo,Credit Card,Pending,2.6,NaN,False,False,440.73
3,ORD-44084,Dress,Dress,Adidas,Blue,Medium,Unisex,Linen,Summer,20.82,...,2024/07/02,"July 14, 2024",Dubai,Installment,Pending,4.8,Defective,False,False,249.32
4,ORD-76192,Blazer,Blazer,Levi'S,Blue,Small,Female,Nylon,Spring,310.14,...,2023-08-10,NaN,Dubai,Debit Card,Processing,2.8,NaN,False,False,4651.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,ORD-84524,T-Shirt,Tshirts,Forever21,Green,Medium,Male,Nylon,Winter,443.27,...,2024/08/26,29-08-2024,Casablanca,Debit Card,Pending,NaN,NaN,False,False,5762.00
7114,ORD-58627,Jeans,Jeans,H&M,Yellow,Extra Small,Female,Linen,Autumn,364.27,...,2022/01/02,2022-01-03,Amman,Installment,Cancelled,1.3,NaN,False,False,1456.36
7116,ORD-88951,Dress,Dress,H&M,Green,Extra Extra Large,Male,Leather,Summer,373.65,...,01/05/2024,02/05/2024,Riyadh,Debit Card,Delivered,2.9,Wrong size,False,False,4856.65
7117,ORD-24646,Coat,Coat,Zara,Brown,Medium,Kids,Polyester,Winter,395.10,...,02-11-2024,22/02/2024,Dubai,Credit Card,Processing,1.4,Late delivery,False,False,5530.53
7119,ORD-65256,Coat,Coat,Nike,Blue,Extra Extra Large,Unisex,Denim,Winter,247.43,...,2022-10-26,2022/11/03,DUBAI,installment,Pending,3.6,NaN,False,False,1978.72

In [ ]:
clean_df['calculated_Revenue'].describe()

count    6008.000000
mean     2662.643494
std      2204.814114
min         9.200000
25%       850.200000
50%      2096.750000
75%      3936.792500
max      9974.550000
Name: calculated_Revenue, dtype: float64

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6008 entries, 0 to 7119
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               6008 non-null   object
 1   product_name           6008 non-null   object
 2   category               6008 non-null   object
 3   brand                  6008 non-null   object
 4   color                  6008 non-null   object
 5   size                   6008 non-null   object
 6   gender                 6008 non-null   object
 7   material               6008 non-null   object
 8   season                 5717 non-null   object
 9   unit_price             6008 non-null   float64
 10  discount               6008 non-null   float64
 11  quantity               6008 non-null   float64
 12  total_sales            5344 non-null   float64
 13  order_date             5397 non-null   object
 14  shipping_date          4999 non-null   object
 15  region                 6008 non-null   object
 16  payment_method         6008 non-null   object
 17  order_status           6008 non-null   object
 18  customer_rating        5547 non-null   object
 19  return_reason          2433 non-null   object
 20  invalid_price_flag     6008 non-null   bool
 21  invalid_quantity_flag  6008 non-null   bool
 22  calculated_Revenue     6008 non-null   float64
dtypes: bool(2), float64(5), object(16)
memory usage: 1.0+ MB

In [ ]:
clean_df['order_date'].unique()

array(['13/06/2024', '2023-09-14', 'December 30, 2024', ...,
       'December 21, 2022', '2024/08/26', '2022-10-26'], dtype=object)

In [ ]:
clean_df['order_date'] = pd.to_datetime(
    clean_df['order_date'],
    errors='coerce',
     format='mixed'
)

In [ ]:
clean_df['order_date'].dtype

dtype('<M8[ns]')

In [ ]:
clean_df['order_date'].unique()

<DatetimeArray>
['2024-06-13 00:00:00', '2023-09-14 00:00:00', '2024-12-30 00:00:00',
 '2024-07-02 00:00:00', '2023-08-10 00:00:00', '2022-01-09 00:00:00',
 '2023-07-21 00:00:00',                 'NaT', '2023-10-24 00:00:00',
 '2023-03-25 00:00:00',
 ...
 '2022-04-30 00:00:00', '2024-04-29 00:00:00', '2022-04-26 00:00:00',
 '2024-07-11 00:00:00', '2023-02-13 00:00:00', '2024-12-01 00:00:00',
 '2024-12-05 00:00:00', '2022-05-25 00:00:00', '2022-02-28 00:00:00',
 '2022-09-19 00:00:00']
Length: 1089, dtype: datetime64[ns]

In [ ]:
clean_df['year'] = clean_df['order_date'].dt.year

In [ ]:
clean_df['month'] = clean_df['order_date'].dt.month

In [ ]:
clean_df['day'] = clean_df['order_date'].dt.day_name()

In [ ]:
clean_df['order_date'].isna().sum()

np.int64(611)

In [ ]:
clean_df['order_date']=clean_df['order_date'].fillna(clean_df['order_date'].mode()[0])

In [ ]:
clean_df['order_date'].isna().sum()

np.int64(0)

In [ ]:
clean_df['shipping_date'].unique()

array(['2024-06-21', '18-09-2023', 'January 01, 2025', ..., '09/02/2022',
       '29-08-2024', '02/05/2024'], dtype=object)

In [ ]:
clean_df['shipping_date']=pd.to_datetime(
    clean_df['shipping_date'],
    errors='coerce',
     format='mixed'
)

In [ ]:
clean_df['shipping_date'].unique()

<DatetimeArray>
['2024-06-21 00:00:00', '2023-09-18 00:00:00', '2025-01-01 00:00:00',
 '2024-07-14 00:00:00',                 'NaT', '2022-01-16 00:00:00',
 '2023-07-25 00:00:00', '2022-12-01 00:00:00', '2023-03-04 00:00:00',
 '2022-04-20 00:00:00',
 ...
 '2023-11-03 00:00:00', '2023-03-06 00:00:00', '2023-10-20 00:00:00',
 '2025-06-01 00:00:00', '2024-03-09 00:00:00', '2025-01-08 00:00:00',
 '2022-07-03 00:00:00', '2024-07-21 00:00:00', '2022-10-21 00:00:00',
 '2023-11-11 00:00:00']
Length: 1101, dtype: datetime64[ns]

In [ ]:
clean_df['shipping_date'].isna().sum()

np.int64(1009)

In [ ]:
clean_df['shipping_date']=clean_df['shipping_date'].fillna(clean_df['shipping_date'].mode()[0])

In [ ]:
clean_df['shipping_date'].isna().sum()

np.int64(0)

In [ ]:
clean_df[clean_df['shipping_date'] < clean_df['order_date']]

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,...,payment_method,order_status,customer_rating,return_reason,invalid_price_flag,invalid_quantity_flag,calculated_Revenue,year,month,day
10,ORD-67912,Sweater,Sweater,Uniqlo,Pink,Extra Extra Large,Male,Linen,Summer,464.100000,...,Cash,Delivered,2.7,Changed mind,False,False,8352.970000,2023.0,3.0,Saturday
24,ORD-99791,Jeans,Jeans,Nike,Blue,Small,Male,Polyester,Autumn,467.060000,...,debit card,Processing,1.0,NaN,False,False,466.170000,2022.0,5.0,Monday
27,ORD-28083,Jeans,Jeans,Puma,White,Extra Extra Large,Unisex,Linen,Winter,20.560000,...,Installment,Cancelled,3.3,NaN,False,False,163.810000,2022.0,12.0,Tuesday
30,ORD-13515,Blazer,Blazer,Adidas,Brown,Extra Extra Large,Unisex,Polyester,Autumn,219.830000,...,Online,Processing,2.4,NaN,False,False,4395.960000,2023.0,9.0,Tuesday
31,ORD-37455,Jacket,Jacket,Nike,Black,Extra Extra Large,Unisex,Linen,Summer,485.490000,...,Credit Card,Cancelled,NaN,Wrong size,False,False,9708.970000,2024.0,8.0,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7069,ORD-56385,Hoodie,Hoodie,Mango,Blue,Large,Unisex,Wool,Summer,243.035621,...,Online,Delivered,NaN,Late delivery,False,False,1700.549347,2023.0,12.0,Monday
7078,ORD-34933,Jacket,Jacket,Gucci,Purple,Large,Male,Polyester,Winter,55.170000,...,Credit Card,Returned,2.1,Defective,False,False,495.550000,2024.0,5.0,Wednesday
7080,ORD-27720,Jacket,Jacket,Nike,Green,Extra Extra Large,Male,Denim,Summer,221.820000,...,Online,Returned,3.8,NaN,False,False,3548.430000,2023.0,4.0,Monday
7081,ORD-75502,Sweater,Sweater,Mango,Purple,Extra Large,Unisex,Linen,Winter,373.530000,...,Cash,Returned,7,Late delivery,False,False,2987.470000,2023.0,11.0,Tuesday
7091,ORD-49282,Shorts,Shorts,Gucci,Grey,Large,Kids,Linen,Winter,301.250000,...,Credit Card,Processing,NaN,NaN,False,False,6024.180000,2024.0,11.0,Friday

In [ ]:
(clean_df['shipping_date'] - clean_df['order_date']).describe()

count                           6008
mean     123 days 11:05:06.790945406
std      261 days 11:51:12.449288932
min              -319 days +00:00:00
25%                  4 days 00:00:00
50%                 10 days 00:00:00
75%                122 days 00:00:00
max               1075 days 00:00:00
dtype: object

In [ ]:
clean_df['invalid_date_flag'] = clean_df['shipping_date'] < clean_df['order_date']

In [ ]:
clean_df2 = clean_df[~clean_df['invalid_date_flag']].copy()

In [ ]:
clean_df2

,order_id,product_name,category,brand,color,size,gender,material,season,unit_price,...,order_status,customer_rating,return_reason,invalid_price_flag,invalid_quantity_flag,calculated_Revenue,year,month,day,invalid_date_flag
0,ORD-33477,Hoodie,Hoodie,Uniqlo,Brown,Extra Small,Male,Silk,Summer,23.96,...,Cancelled,2.4,NaN,False,False,430.64,2024.0,6.0,Thursday,False
1,ORD-93931,Jacket,Jacket,H&M,Brown,Extra Extra Large,Male,Nylon,Winter,166.89,...,Delivered,2.9,Defective,False,False,3170.23,2023.0,9.0,Thursday,False
2,ORD-28582,Hoodie,Hoodie,Forever21,Red,Extra Small,Kids,Denim,Autumn,110.40,...,Pending,2.6,NaN,False,False,440.73,2024.0,12.0,Monday,False
3,ORD-44084,Dress,Dress,Adidas,Blue,Medium,Unisex,Linen,Summer,20.82,...,Pending,4.8,Defective,False,False,249.32,2024.0,7.0,Tuesday,False
4,ORD-76192,Blazer,Blazer,Levi'S,Blue,Small,Female,Nylon,Spring,310.14,...,Processing,2.8,NaN,False,False,4651.52,2023.0,8.0,Thursday,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,ORD-84524,T-Shirt,Tshirts,Forever21,Green,Medium,Male,Nylon,Winter,443.27,...,Pending,NaN,NaN,False,False,5762.00,2024.0,8.0,Monday,False
7114,ORD-58627,Jeans,Jeans,H&M,Yellow,Extra Small,Female,Linen,Autumn,364.27,...,Cancelled,1.3,NaN,False,False,1456.36,2022.0,1.0,Sunday,False
7116,ORD-88951,Dress,Dress,H&M,Green,Extra Extra Large,Male,Leather,Summer,373.65,...,Delivered,2.9,Wrong size,False,False,4856.65,2024.0,1.0,Friday,False
7117,ORD-24646,Coat,Coat,Zara,Brown,Medium,Kids,Polyester,Winter,395.10,...,Processing,1.4,Late delivery,False,False,5530.53,2024.0,2.0,Sunday,False
7119,ORD-65256,Coat,Coat,Nike,Blue,Extra Extra Large,Unisex,Denim,Winter,247.43,...,Pending,3.6,NaN,False,False,1978.72,2022.0,10.0,Wednesday,False

In [ ]:
clean_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5383 entries, 0 to 7119
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5383 non-null   object
 1   product_name           5383 non-null   object
 2   category               5383 non-null   object
 3   brand                  5383 non-null   object
 4   color                  5383 non-null   object
 5   size                   5383 non-null   object
 6   gender                 5383 non-null   object
 7   material               5383 non-null   object
 8   season                 5119 non-null   object
 9   unit_price             5383 non-null   float64
 10  discount               5383 non-null   float64
 11  quantity               5383 non-null   float64
 12  total_sales            4782 non-null   float64
 13  order_date             5383 non-null   datetime64[ns]
 14  shipping_date          5383 non-null   datetime64[ns]
 15  region                 5383 non-null   object
 16  payment_method         5383 non-null   object
 17  order_status           5383 non-null   object
 18  customer_rating        4980 non-null   object
 19  return_reason          2189 non-null   object
 20  invalid_price_flag     5383 non-null   bool
 21  invalid_quantity_flag  5383 non-null   bool
 22  calculated_Revenue     5383 non-null   float64
 23  year                   4864 non-null   float64
 24  month                  4864 non-null   float64
 25  day                    4864 non-null   object
 26  invalid_date_flag      5383 non-null   bool
dtypes: bool(3), datetime64[ns](2), float64(7), object(15)
memory usage: 1.0+ MB

In [ ]:
clean_df2['region'].unique()

array(['Doha', 'Amman', 'Cairo', 'Dubai', 'Casablanca', 'riyadh', 'Dubay',
       '  Tunis  ', 'عمان', 'الدوحة', 'Riyadh', '  Alexandria  ',
       'Kuwait', 'Cario', 'Tunis City', 'tunis', 'الكويت', 'Beirut',
       'Alex', 'CAIRO', 'Alexandria', 'دبي', '  Amman  ', 'DOHA', 'بيروت',
       'Tunis', 'الاسكندرية', 'Aman', 'Kuwait City', 'alexandria',
       'amman', '  Cairo  ', 'kuwait', 'Casa', 'RIYADH', 'Alexa', 'ALEX',
       'TUNIS', 'Riyad', 'القاهرة', 'CASA', 'KUWAIT', 'Bayrut', 'AMMAN',
       'الرياض', 'Al Cairo', 'doha', 'BEIRUT', 'كازابلانكا', 'cairo',
       'Dooha', 'DUBAI', 'casablanca', '  Casablanca  ', 'dubai', 'تونس',
       'beirut', '  Doha  ', '  Kuwait  ', '  Riyadh  ', '  Dubai  ',
       '  Beirut  '], dtype=object)

In [ ]:
clean_df2['region'] = (
  clean_df2['region']
    .astype(str)
    .str.strip()
    .str.title()
)

In [ ]:
region_map = {

    # Cairo
    'Cario': 'Cairo',
    'Al Cairo': 'Cairo',
    'CAIRO': 'Cairo',
    'Cairo': 'Cairo',
    'القاهرة': 'Cairo',

    # Alexandria
    'Alex': 'Alexandria',
    'Alexa': 'Alexandria',
    'ALEX': 'Alexandria',
    'Alexandria': 'Alexandria',
    'الاسكندرية': 'Alexandria',

    # Riyadh
    'Riyad': 'Riyadh',
    'RIYADH': 'Riyadh',
    'الرياض': 'Riyadh',
    'Riyadh': 'Riyadh',

    # Dubai
    'Dubay': 'Dubai',
    'Dooha': 'Dubai',
    'Dubai': 'Dubai',
    'دبي': 'Dubai',

    # Doha
    'DOHA': 'Doha',
    'Dooha': 'Doha',
    'الدوحة': 'Doha',
    'Doha': 'Doha',

    # Amman
    'Aman': 'Amman',
    'AMMAN': 'Amman',
    'عمان': 'Amman',
    'Amman': 'Amman',

    # Kuwait
    'KUWAIT': 'Kuwait',
    'Kuwait City': 'Kuwait',
    'الكويت': 'Kuwait',
    'Kuwait': 'Kuwait',

    # Beirut
    'Bayrut': 'Beirut',
    'BEIRUT': 'Beirut',
    'بيروت': 'Beirut',
    'Beirut': 'Beirut',

    # Casablanca
    'Casa': 'Casablanca',
    'CASA': 'Casablanca',
    'كازابلانكا': 'Casablanca',
    'Casablanca': 'Casablanca',

    # Tunis
    'Tunis City': 'Tunis',
    'TUNIS': 'Tunis',
    'tunis': 'Tunis',
    'تونس': 'Tunis',
    'Tunis': 'Tunis'
}

In [ ]:
clean_df2['region'] = clean_df2['region'].replace(region_map)

In [ ]:
clean_df2['region'].unique()

array(['Doha', 'Amman', 'Cairo', 'Dubai', 'Casablanca', 'Riyadh', 'Tunis',
       'Alexandria', 'Kuwait', 'Beirut'], dtype=object)

In [ ]:
clean_df2['region'].value_counts()

region
Casablanca    565
Kuwait        561
Doha          560
Dubai         553
Riyadh        540
Tunis         535
Cairo         532
Amman         528
Alexandria    516
Beirut        493
Name: count, dtype: int64

In [ ]:
clean_df2['payment_method'].unique()

array(['Online', 'Debit Card', 'Credit Card', 'Installment', 'Cash',
       'installment', 'credit card', 'cash', 'online', 'debit card'],
      dtype=object)

In [ ]:
clean_df2['payment_method']=clean_df2['payment_method'].str.strip().str.title()

In [ ]:
payment_map = {
    'Debit Card': 'Debit Card',
    'Credit Card': 'Credit Card',
    'Cash': 'Cash',
    'Installment': 'Installment',
    'Online': 'Online'
}

In [ ]:
clean_df2['payment_method']=clean_df2['payment_method'].replace(payment_map)

In [ ]:
clean_df2['payment_method'].unique()

array(['Online', 'Debit Card', 'Credit Card', 'Installment', 'Cash'],
      dtype=object)

In [ ]:
clean_df2['payment_method'].value_counts()

payment_method
Cash           1119
Online         1094
Debit Card     1079
Installment    1063
Credit Card    1028
Name: count, dtype: int64

In [ ]:
clean_df2['order_status'].str.strip().str.title().unique()

array(['Cancelled', 'Delivered', 'Pending', 'Processing', 'Returned'],
      dtype=object)

In [ ]:
clean_df2['order_status']=clean_df2['order_status'].str.strip().str.title()

In [ ]:
clean_df2['order_status'].value_counts()

order_status
Pending       1098
Processing    1091
Delivered     1089
Returned      1065
Cancelled     1040
Name: count, dtype: int64

In [ ]:
clean_df2['customer_rating'].unique()

array(['2.4', '2.9', '2.6', '4.8', '2.8', '2.3', '2.0', '3.7', '6', '9',
       nan, '3.2', '1.6', '1.8', '3.6', '4.4', '4.1', '2.5', '8', '1.2',
       '2.2', '3.8', '4.0', '1.3', '3.5', '4.7', '3.1', '1.5', '2.1',
       '2.7', '1.0', '4.2', '3.9', '4.6', '3.0', '4.5/5', '5.0', '3.3',
       '1.4', '1.9', '4.5', '10', '3.4', '1.7', '4.9', '1.1', '4.3', '7',
       '1.3/5', '2.3/5', '3.1/5', '4.6/5', '4.4/5', '2.1/5', '4.9/5',
       '1.9/5', '1.0/5', '1.6/5', '4.2/5', '2.6/5', '3.7/5', '1.1/5',
       '1.7/5', '1.5/5', '4.3/5', '3.5/5', '2.5/5', '2.9/5', '3.0/5',
       '2.0/5', '3.6/5', '2.7/5', '3.3/5', '1.4/5', '4.0/5', '3.9/5',
       '4.1/5', '4.7/5', '2.8/5', '2.4/5', '3.2/5', '3.8/5', '3.4/5',
       '5.0/5', '1.2/5', '2.2/5', '4.8/5', '1.8/5'], dtype=object)

In [ ]:
clean_df2['customer_rating'].unique()

array(['2.4', '2.9', '2.6', '4.8', '2.8', '2.3', '2.0', '3.7', '6', '9',
       nan, '3.2', '1.6', '1.8', '3.6', '4.4', '4.1', '2.5', '8', '1.2',
       '2.2', '3.8', '4.0', '1.3', '3.5', '4.7', '3.1', '1.5', '2.1',
       '2.7', '1.0', '4.2', '3.9', '4.6', '3.0', '4.5/5', '5.0', '3.3',
       '1.4', '1.9', '4.5', '10', '3.4', '1.7', '4.9', '1.1', '4.3', '7',
       '1.3/5', '2.3/5', '3.1/5', '4.6/5', '4.4/5', '2.1/5', '4.9/5',
       '1.9/5', '1.0/5', '1.6/5', '4.2/5', '2.6/5', '3.7/5', '1.1/5',
       '1.7/5', '1.5/5', '4.3/5', '3.5/5', '2.5/5', '2.9/5', '3.0/5',
       '2.0/5', '3.6/5', '2.7/5', '3.3/5', '1.4/5', '4.0/5', '3.9/5',
       '4.1/5', '4.7/5', '2.8/5', '2.4/5', '3.2/5', '3.8/5', '3.4/5',
       '5.0/5', '1.2/5', '2.2/5', '4.8/5', '1.8/5'], dtype=object)

In [ ]:
clean_df2['customer_rating'] = (
    clean_df2['customer_rating'].str.extract(r'(\d+\.?\d*)')
)

In [ ]:
clean_df2['customer_rating'].unique()

array(['2.4', '2.9', '2.6', '4.8', '2.8', '2.3', '2.0', '3.7', '6', '9',
       nan, '3.2', '1.6', '1.8', '3.6', '4.4', '4.1', '2.5', '8', '1.2',
       '2.2', '3.8', '4.0', '1.3', '3.5', '4.7', '3.1', '1.5', '2.1',
       '2.7', '1.0', '4.2', '3.9', '4.6', '3.0', '4.5', '5.0', '3.3',
       '1.4', '1.9', '10', '3.4', '1.7', '4.9', '1.1', '4.3', '7'],
      dtype=object)

In [ ]:
clean_df2['customer_rating']=clean_df2['customer_rating'].astype(float)

In [ ]:
clean_df2.loc[clean_df2['customer_rating'] > 5, 'customer_rating'] = 5

In [ ]:
clean_df2['customer_rating'].unique()

array([2.4, 2.9, 2.6, 4.8, 2.8, 2.3, 2. , 3.7, 5. , nan, 3.2, 1.6, 1.8,
       3.6, 4.4, 4.1, 2.5, 1.2, 2.2, 3.8, 4. , 1.3, 3.5, 4.7, 3.1, 1.5,
       2.1, 2.7, 1. , 4.2, 3.9, 4.6, 3. , 4.5, 3.3, 1.4, 1.9, 3.4, 1.7,
       4.9, 1.1, 4.3])

In [ ]:
clean_df2['customer_rating'].fillna(0,inplace=True)

/tmp/ipykernel_27764/1635137218.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_df2['customer_rating'].fillna(0,inplace=True)

In [ ]:
clean_df2['customer_rating'].unique()

array([2.4, 2.9, 2.6, 4.8, 2.8, 2.3, 2. , 3.7, 5. , 0. , 3.2, 1.6, 1.8,
       3.6, 4.4, 4.1, 2.5, 1.2, 2.2, 3.8, 4. , 1.3, 3.5, 4.7, 3.1, 1.5,
       2.1, 2.7, 1. , 4.2, 3.9, 4.6, 3. , 4.5, 3.3, 1.4, 1.9, 3.4, 1.7,
       4.9, 1.1, 4.3])

In [ ]:
clean_df2['return_reason'].unique()

array([nan, 'Defective', 'Late delivery', 'Changed mind', 'Wrong size'],
      dtype=object)

In [ ]:
clean_df2['return_reason']=clean_df2['return_reason'].str.strip().str.title()

In [ ]:
clean_df2['return_reason'].unique()

array([nan, 'Defective', 'Late Delivery', 'Changed Mind', 'Wrong Size'],
      dtype=object)

In [ ]:
Cleaned_Clothes=clean_df2.to_csv('Cleaned_Clothes.csv',index=False)